app = "sanberapp"

[build]
  builder = "heroku/buildpacks:20"

[env]
  APP_ENV = "production"
  APP_DEBUG = "false"
  LOG_CHANNEL = "stderr"
  DB_CONNECTION = "sqlite"
  DB_DATABASE = "/app/database/database.sqlite"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[mounts]]
  source = "data"
  destination = "/app/database"

[processes]
  app = "php artisan serve --host 0.0.0.0 --port 8080"
